.github/workflows/test.yml

feat(ci): test ci with cairo1 dockerized cli

---

src/data_structures/merkle_tree.cairo
src/math/extended_euclidean_algorithm.cairo
src/math/fibonacci.cairo
src/tests/merkle_tree_test.cairo

Merkle Tree compute root

---

README.md
src/math.cairo
src/math/karatsuba.cairo
src/tests.cairo
src/tests/karatsuba_test.cairo
src/utils.cairo

- Implement Karatsuba Multiplication Algorithm
- Add the algorithm to the math module
- Add some aux methods to the utils file
- Units tests for Karatsuba
Issue Number: [#6](https://github.com/keep-starknet-strange/quaireaux/issues/6)
N/A

feat: add Karatsuba Multiplication

---

README.md
src/math.cairo
src/math/perfect_number.cairo
src/tests.cairo
src/tests/perfect_number_test.cairo

* Implement Perfect Number Algorithm
* Add the algorithm to the math module
* Units tests for Perfect Number
Issue Number: #12 
N/A

feat: Add Perfect Number

---

README.md
src/demo.cairo
src/math.cairo
src/math/perfect_number.cairo
src/tests.cairo

Fix issue with Perfect Number Test

---

README.md
src/math.cairo
src/math/armstrong_number.cairo
src/tests.cairo
src/tests/armstrong_number_test.cairo
src/utils.cairo

* Implement Armstrong Number Algorithm
* Add the algorithm to the math module
* Units tests
Issue Number: #5 
-
-
-

feat: Add Armstrong Number

---

README.md
src/math.cairo
src/math/gcd_of_n_numbers.cairo
src/tests.cairo
src/tests/gcd_of_n_numbers_test.cairo

- Implements the Greatest Common Divisor for an array of N values
- Add unit testing 
Repository doesn't contain the algorithm allowing to calculate the GCD for an array of N values.
Issue Number: #25 
Repository contains the algorithm allowing to calculate the GCD for an array of N values.

feat: gcd of N numbers

---

README.md
Scarb.toml

- Quaireaux can now be used as dependency in Scarb projects 🎉
- I couldn't find any version number in the current state of the repo, so I picked an arbitrary one.
- https://github.com/software-mansion/scarb/pull/69/commits/457bd04b6c8098bc6d3c081c3380aa58b088f2c3 😉

Add Scarb.toml

---

.github/workflows/test.yml
src/data_structures/merkle_tree.cairo
src/data_structures/queue.cairo
src/tests/queue_test.cairo
src/tests/zellers_congruence_test.cairo
src/utils.cairo

update: latest Cairo 1

---

src/math.cairo
src/math/fast_power.cairo
src/tests.cairo
src/tests/fast_power_test.cairo
src/utils.cairo

- Implements the fast powering algorithm
- Add integer libraries imports
- Add unit testing
Repository doesn't contain the fast powering algorithm.
Issue Number: #34 
- Fast powering algorithm
- Unit testing for fast powering algorithm

feat: fast power

---

src/lib.cairo
src/sorting.cairo
src/sorting/merge_sort.cairo
src/tests.cairo
src/tests/mergesort_test.cairo
src/utils.cairo

- Implement MergeSort sorting algorithm
- Create a new `sorting` module 
- Unit tests for MergeSort
- Add `split` and `fill` array utils methods
Issue Number: #23 
N/A

feat: MergeSort

---

README.md
src/math.cairo
src/sorting.cairo
src/sorting/bubble_sort.cairo
src/tests.cairo
src/tests/bubblesort_test.cairo

- Bubble sort implementation (function and tests)

feat: bubble_sort

---

README.md
src/math.cairo
src/math/collatz_sequence.cairo
src/tests.cairo
src/tests/collatz_sequence_test.cairo

* Implement Collatz Sequence Algorithm
* Add the algorithm to the math module
* Units tests for Collatz Sequence
Issue Number: #30 
N/A

feat: Add Collatz Sequence

---

README.md
src/math.cairo
src/math/aliquot_sum.cairo
src/tests.cairo
src/tests/aliquot_sum_test.cairo

* Implement Aliquot Sum Algorithm
* Add the algorithm to the math module
* Units tests for Aliquot Sum
Issue Number: #29 
N/A

feat: Add Aliquot Sum 

---

README.md

[Scarb 0.1.0-alpha.3](https://github.com/software-mansion/scarb/releases/tag/v0.1.0-alpha.2) finally supports that 🎉

Update installation instructions to suggest pulling Scarb from Git

---

.github/workflows/test.yml
src/data_structures.cairo
src/data_structures/queue.cairo
src/data_structures/stack.cairo
src/tests/stack_test.cairo
src/tests/utils_test.cairo
src/utils.cairo

Implements an array-based u256 stack
A functional array-based U256Stack
Issue Number: Fixes #16 
-
-
-

feat: Stack::<u256>

---

.github/workflows/test.yml
src/data_structures/merkle_tree.cairo
src/math/armstrong_number.cairo
src/math/extended_euclidean_algorithm.cairo
src/math/fast_power.cairo
src/math/fibonacci.cairo
src/math/gcd_of_n_numbers.cairo
src/math/karatsuba.cairo
src/math/perfect_number.cairo
src/sorting/merge_sort.cairo
src/utils.cairo

⬆️ latest cairo

---

src/math.cairo
src/math/signed_integers.cairo
src/tests.cairo
src/tests/signed_integers_test.cairo

Signed integers : i9, i17, i33, i65, i129
There are no implementations and operations on signed integers.
- functions for signed integer operations
- implement traits to use operators on it
- unit testing

feat: Implementation of signed integers

---

quaireaux/math/README.md
quaireaux/math/src/aliquot_sum.cairo
quaireaux/math/src/armstrong_number.cairo
quaireaux/math/src/collatz_sequence.cairo
quaireaux/math/src/fast_power.cairo
quaireaux/math/src/math.cairo

Some refactoring of some math files and adding a documentation to briefly describe the purpose of each algorithm.
Will make another PR with the rest of math later.

refactor some file and add documentation

---

quaireaux/data_structures/src/lib.cairo
quaireaux/data_structures/src/tests.cairo
quaireaux/data_structures/src/tests/vec_test.cairo
quaireaux/data_structures/src/vec.cairo

Issue Number: Closes #55 
- Mutable vec data structure
-
-

feat: Vec data structure

---

quaireaux/data_structures/src/array_ext.cairo
quaireaux/data_structures/src/data_structures.cairo
quaireaux/data_structures/src/tests/array_ext_test.cairo
quaireaux/math/src/aliquot_sum.cairo
quaireaux/math/src/math.cairo
quaireaux/math/src/perfect_number.cairo
quaireaux/sorting/src/bubble_sort.cairo

This PR should solve https://github.com/keep-starknet-strange/quaireaux/issues/75.  
I also fixed the previous interface and now all fn should use @ Array instead of Array.
I also took some time to update `x = x + 1` to `x += 1`
Some fn where update to return an Option instead of panicking. 
This PR took me a about 3 hours

array ext with span 

---

alexandria/data_structures/src/merkle_tree.cairo

There's an unnecessary copy.
The PR removes the copy, probably saves a couple of Cairo steps 😅 
The smallest of updates, was just coincidentally looking at that part of the lib and noticed it.

chore: removing a copy

---

.github/workflows/test.yml
README.md
alexandria/math/src/lib.cairo
alexandria/math/src/signed_integers.cairo
alexandria/math/src/tests.cairo
alexandria/sorting/src/bubble_sort.cairo

Update the repo to cairo V1 https://github.com/starkware-libs/cairo/releases/tag/v1.0.0
Fixed the signed integers file
Update the readme: should fix https://github.com/keep-starknet-strange/alexandria/issues/79
Copy pasted + updated what was done in https://github.com/keep-starknet-strange/alexandria/pull/80 so this one can also be closed

update v1 + signed back + update readme

---

alexandria/math/src/math.cairo
alexandria/math/src/tests/math_test.cairo

* cleaner impl of `pow`
* added `pow` test case with different base (so we know we're not testing only pow2)
* inline comments updates to reflect reality

dev: cleaner pow fn

---

alexandria/data_structures/src/merkle_tree.cairo

Issue Number: #107
- Alexandria data structures compile now

fix merkel tree compilation error

---

alexandria/searching/README.md

Fix: minor typos

---

.github/workflows/test.yml
alexandria/data_structures/src/array_ext.cairo
alexandria/data_structures/src/merkle_tree.cairo
alexandria/data_structures/src/tests/array_ext_test.cairo
alexandria/data_structures/src/vec.cairo
alexandria/encoding/src/base64.cairo
alexandria/math/src/sha256.cairo
alexandria/math/src/tests/math_test.cairo
alexandria/math/src/tests/signed_integers_test.cairo
alexandria/searching/src/binary_search.cairo
alexandria/sorting/src/bubble_sort.cairo
alexandria/sorting/src/tests/merge_sort_test.cairo

chore: use cairo 1.1.0 features

---

README.md

Update README to specify that there are now 5 crates

Update README.md - 5 packages

---

Makefile
alexandria/data_structures/src/array_ext.cairo
alexandria/math/README.md
alexandria/math/src/ed25519.cairo
alexandria/math/src/lib.cairo
alexandria/math/src/math.cairo
alexandria/math/src/mod_arithmetics.cairo
alexandria/math/src/sha512.cairo
alexandria/math/src/tests.cairo
alexandria/math/src/tests/ed25519_test.cairo
alexandria/math/src/tests/mod_arithmetics_test.cairo

Issue Number: Closes #113 and #115

Implement ed25519 signature verification

---

.github/workflows/test.yml
README.md

Now that v2.0.0.0 is released, I updated the repo to that version

Update to v2.0.0

---

src/math/fast_power.cairo

Fast power can now better use u256

Cleaning fast_power to use u256

---

src/sorting/sorting.cairo

Remove doc related to index as it was removed

Update Sorting.cairo doc

---

src/math/src/karatsuba.cairo
src/math/src/tests/sha512_test.cairo

Follow good practices

---

src/storage/src/list.cairo
src/storage/src/tests/list_test.cairo

Issue Number: [#177](https://github.com/keep-starknet-strange/alexandria/issues/177) 
- Added a clean component to List 
- Added unit test related to this component

feat: Add clean method for list

---

src/storage/src/tests/list_test.cairo

fix(sn storage): macro name typo

---

.all-contributorsrc
README.md

add eikix contributor

---

src/storage/src/list.cairo
src/storage/src/tests/list_test.cairo

Refactored the List type to:
- Return SyscallResults instead of panicking in case of storage interaction errors
Added features to make it easier to interact with low-level storage:
- ListTrait::new() to instanciate a new list at a given storage address
- ListTrait::fetch() to fetch a list stored at a given storage address
- Tested these features
Added documentation on List functions
Optimized some functions with inlining

refactor: List

---

.github/workflows/test.yml
.tool-versions
Scarb.lock
Scarb.toml
src/data_structures/Scarb.toml
src/data_structures/src/byte_array_ext.cairo
src/data_structures/src/tests/byte_array_ext_test.cairo

Bumped alexandria_data_structures version number as there are breaking changes in ByteArray serde
-
-
-
Bumped alexandria_data_structures version number as there are breaking changes in ByteArray serde

chore: bump cairo 2.4.0-rc2

---

src/math/src/mod_arithmetics.cairo

```
sub_mod gas consumption
---------------------------
test ::sub_mod_2_test ... ok (gas usage est.: 418780)
test ::sub_mod_1_test ... ok (gas usage est.: 418780)
test ::sub_mod_test ...   ok (gas usage est.: 444500)
```
```
sub_mod gas optimised
---------------------------
test ::sub_mod_2_test ... ok (gas usage est.: 330380)
test ::sub_mod_1_test ... ok (gas usage est.: 330380)
test ::sub_mod_test ...   ok (gas usage est.: 356100)
```
**Removed** modulo on results,
For `a >= b`,
result goes from `0` to `a`, `a` already `mod`ed
For `a < b`,
result goes from `modulo - b` to `modulo - 1`, `b` already `mod`ed

optimise sub_mod

---

src/math/README.md
src/math/src/fast_root.cairo
src/math/src/lib.cairo
src/math/src/tests.cairo
src/math/src/tests/fast_root_test.cairo

This PR adds fast root using Newton-Raphson method
- solving square / cube / N-th root using Newton-Raphson method.

feat: add fast root using Newton-Raphson method

---

src/math/README.md
src/math/src/is_power_of_two.cairo
src/math/src/lib.cairo
src/math/src/tests.cairo
src/math/src/tests/is_power_of_two_test.cairo

This PR adds `is_power_of_two()` checker.
- checking whether a number is power of two.

feat: add is power of two checker

---

src/math/README.md
src/math/src/is_prime.cairo
src/math/src/lib.cairo
src/math/src/tests.cairo
src/math/src/tests/is_prime_test.cairo

This PR adds a function to check if the given number is a prime.
- checking if the given number is a prime.

feat: add is_prime

---

src/data_structures/src/bit_array.cairo
src/data_structures/src/byte_reader.cairo
src/math/README.md
src/math/src/karatsuba.cairo
src/math/src/mod_arithmetics.cairo

Found a few errors, one is in the README file, rest are in comments

chore: a bit of proofreading

---

src/math/src/i257.cairo

Fix negative zero for i257 eq gt

---

src/data_structures/src/array_ext.cairo

Using new syntax where possible on array_ext

Array_ext improvement

---

src/sorting/src/bubble_sort.cairo
src/sorting/src/interface.cairo
src/sorting/src/lib.cairo
src/sorting/src/merge_sort.cairo
src/sorting/src/quick_sort.cairo
src/sorting/src/tests/bubble_sort_test.cairo
src/sorting/src/tests/merge_sort_test.cairo
src/sorting/src/tests/quick_sort_test.cairo

Rework the sorting package to introduce a common API that all sorting algorithm should follow from now on.
BREAKING CHANGES: API

Rework sorting

---

src/math/src/i257.cairo

Make public Zeroable on i257 and fix is_zero for negative numbers

Public zeroable on i257

---

src/math/src/ed25519.cairo
src/math/src/mod_arithmetics.cairo
src/math/src/tests/ed25519_test.cairo
src/math/src/tests/mod_arithmetics_test.cairo

- 15% less gas usage via various changes in the ed25519 verification algo

enh: optimise ed25519

---

src/math/src/mod_arithmetics.cairo

```diff
running 3 tests
- test alexandria_math::tests::mod_arithmetics_test::pow_mod_1_test ... ok (gas usage est.: 28413612)
+ test alexandria_math::tests::mod_arithmetics_test::pow_mod_1_test ... ok (gas usage est.: 27142740)
- test alexandria_math::tests::mod_arithmetics_test::pow_mod_2_test ... ok (gas usage est.: 28413612)
+ test alexandria_math::tests::mod_arithmetics_test::pow_mod_2_test ... ok (gas usage est.: 27142740)
- test alexandria_math::tests::mod_arithmetics_test::pow_mod_test ... ok (gas usage est.: 28443352)
+ test alexandria_math::tests::mod_arithmetics_test::pow_mod_test ... ok (gas usage est.: 27173670)
```
No changes in functionality, just slightly faster `pow_mod`.

optimise mod_pow

---

.gitignore
src/math/src/ed25519.cairo
src/math/src/tests/ed25519_test.cairo

```diff
Compiling alexandria_math v0.2.0 (/Users/shramee/www/starknet/alexandria/src/math/Scarb.toml)
Finished release target(s) in 3 seconds
Collected 1 test(s) from alexandria_math package
Running 1 test(s) from src/
[PASS] alexandria_math::tests::ed25519_test::verify_signature_test_3 (gas: ~37305)
-        steps: 5791003
+        steps: 3276058
memory holes: 725540
builtins: ("range_check_builtin": 932625, "bitwise_builtin": 2031)
syscalls: ()
Tests: 1 passed, 0 failed, 0 skipped, 0 ignored, 148 filtered out
```

ed25519 optimisations

---

src/math/src/ed25519.cairo

No changes in the behaviour, just cleaning up old homogenous extended point code.

ed25519: remove extended homogenous point

---

packages/math/src/i257.cairo

- Implemented Display trait for `i257`

feat: implement Display trait for i257

---

packages/bytes/src/bytes.cairo
packages/bytes/src/tests/test_bytes.cairo
packages/bytes/src/tests/test_bytes_store.cairo
packages/bytes/src/utils.cairo
packages/data_structures/src/tests/array_ext.cairo
packages/data_structures/src/tests/queue.cairo
packages/encoding/src/sol_abi/encode.cairo
packages/encoding/src/tests/base64_felt_test.cairo
packages/math/src/bip340.cairo
packages/math/src/ed25519.cairo
packages/math/src/mod_arithmetics.cairo
packages/math/src/sha512.cairo
packages/math/src/tests/bip340_test.cairo
packages/math/src/tests/i257_test.cairo
packages/math/src/tests/mod_arithmetics_test.cairo
packages/math/src/tests/sha512_test.cairo
packages/math/src/trigonometry.cairo
packages/merkle_tree/src/storage_proof.cairo
packages/merkle_tree/src/tests/merkle_tree_test.cairo
packages/merkle_tree/src/tests/storage_proof_test.cairo
packages/merkle_tree/src/tests/storage_proof_test_data.cairo
packages/numeric/src/integers.cairo
packages/searching/src/tests/dijkstra_test.cairo
packages/storage/src/tests/list_test.cairo
packages/utils/src/fmt.cairo

Fixing format issue + cleaning some warnings due to unused imports

Fixing format issue

---

Scarb.lock
Scarb.toml
packages/ascii/Scarb.toml
packages/bytes/Scarb.toml
packages/data_structures/Scarb.toml
packages/data_structures/src/byte_appender.cairo
packages/encoding/Scarb.toml
packages/linalg/Scarb.toml
packages/macros/Scarb.toml
packages/math/Scarb.toml
packages/merkle_tree/Scarb.toml
packages/numeric/Scarb.toml
packages/searching/Scarb.toml
packages/sorting/Scarb.toml
packages/storage/Scarb.toml
packages/utils/Scarb.toml

Version 0.4.0

---

.github/workflows/macros.yml
packages/macros_tests/src/lib.cairo

Fix macros CI bug

---

packages/encoding/src/base58.cairo
packages/encoding/src/lib.cairo
packages/encoding/src/tests.cairo
packages/encoding/src/tests/base58_test.cairo

Implement base58 encoding

---

Scarb.lock
Scarb.toml
packages/ascii/Scarb.toml
packages/bytes/Scarb.toml
packages/data_structures/Scarb.toml
packages/encoding/Scarb.toml
packages/linalg/Scarb.toml
packages/macros/Scarb.toml
packages/math/Scarb.toml
packages/merkle_tree/Scarb.toml
packages/numeric/Scarb.toml
packages/searching/Scarb.toml
packages/sorting/Scarb.toml
packages/storage/Scarb.toml
packages/utils/Scarb.toml
scripts/update_registry.sh

registry script & 0.5.1
