keep-starknet-strange/alexandria

README.md
src/data_structures.cairo
src/data_structures/queue.cairo
src/tests.cairo
src/tests/queue_test.cairo

No support for Queue.
Issue Number: [#7](https://github.com/keep-starknet-strange/quaireaux/issues/7) 
Add queue.cairo
**Queue** struct
**QueueTrait** with the following functions:
- **new**
- **enqueue**
- **dequeue**
- **peek_front**
- **len**
- **is_empty**

feat: Add support for Queue

---

src/math/armstrong_number.cairo
src/math/karatsuba.cairo
src/tests.cairo
src/tests/utils_test.cairo
src/utils.cairo

Add an option to specifiy a base to count digits
Add tests to utils
Currently, `count_digits` only count with base 10 
Specifying a base to count digits makes it simpler to count digits/bytes/nibles 
Calls to `count_digits` need to be updates

Specifiy base to count digits

---

src/data_structures/stack.cairo
src/tests/stack_test.cairo

Uses `ref` instead of a mutable value in `stack.pop()`
-
-
-

fix: use ref in `stack.pop()`

---

quaireaux/math/src/aliquot_sum.cairo
quaireaux/math/src/armstrong_number.cairo
quaireaux/math/src/collatz_sequence.cairo
quaireaux/math/src/extended_euclidean_algorithm.cairo
quaireaux/math/src/fast_power.cairo
quaireaux/math/src/gcd_of_n_numbers.cairo
quaireaux/math/src/karatsuba.cairo
quaireaux/math/src/lib.cairo
quaireaux/math/src/math.cairo
quaireaux/math/src/perfect_number.cairo
quaireaux/math/src/tests.cairo
quaireaux/math/src/tests/math_test.cairo
quaireaux/sorting/src/merge_sort.cairo
quaireaux/utils/src/lib.cairo
quaireaux/utils/src/tests/utils_test.cairo
quaireaux/utils/src/utils.cairo

Utils crate should ultimately contain only stuff that can be used by all other crates and shouldn't be cluttered with code used by only 1 crate
Moved all math related stuff from utils to a math file within math.

moving all math related fn to the math crate

---

quaireaux/math/src/extended_euclidean_algorithm.cairo

Loop is now a reserved keyword with the upcoming Cairo release. I renamed a function called `loop` to `loop_euclidian`
-
-
-

fix: loop keyword reserved

---

alexandria/data_structures/src/tests/vec_test.cairo
alexandria/data_structures/src/vec.cairo

To fetch an element at a particular index in a `Vec`, one has to use `at`
PR implements the `Index` trait to allow for using `[]` operator when fetching Vec elements:
```
let element_at_2 = a_vec[2];
```

feat: vec index trait

---

alexandria/data_structures/src/vec.cairo
alexandria/encoding/src/base64.cairo
alexandria/math/src/fast_power.cairo
alexandria/math/src/sha256.cairo
alexandria/math/src/tests/fast_power_test.cairo
alexandria/searching/src/binary_search.cairo
alexandria/sorting/src/bubble_sort.cairo

Issue Number: #95 
- panic with overflow error for certain inputs
I have choose to change all the parameter types to `u256` instead of using [`u128_wide_mul`](https://github.com/starkware-libs/cairo/blob/77ae28f996c0960ce5cfc926703f60bae8d5db5a/corelib/src/integer.cairo#L66C1-L69).
Because in the loop:
- we would need to do it in 2 places, so 2 type conversions to u256
-  `%` is only implemented for same types we cannot calculate `u256 % u128`, so would need to convert `modulus` to u256 
- after calculating modulus would needs to cast it back to u128
Also for some reason comment mentioned result of function is `felt252` instead of `u128`, so have fixed that as well.

fix: integer overflow in fast_power

---

alexandria/storage/README.md
alexandria/storage/Scarb.toml
alexandria/storage/cairo_project.toml
alexandria/storage/src/lib.cairo
alexandria/storage/src/list.cairo
alexandria/storage/src/tests.cairo
alexandria/storage/src/tests/list_test.cairo

Adding support for array storage (up to 2^32 elements). This feature enables things like:
```rust
#[storage]
struct Storage {
values: List<u256>
}
```
Currently, when you want to store an array of values in a Starknet contracts, you have to resort to sth like this
```rust
struct Storage {
values_count: u32,
values: LegacyMap<u32, u256>
}
```
i.e. have a dictionary where the key is the index of the element. This is cumbersome as you have to take care of properly updating both values and just deal with multiple storage variables all the time.
This PR adds a new data structure called `List` which rectifies the above approach. There's only one storage variable and in general it acts as an "array" from other programming languages that devs …

feat(storage): list

---

alexandria/linalg/src/dot.cairo
alexandria/linalg/src/tests/dot_test.cairo
alexandria/numeric/src/cumsum.cairo
alexandria/numeric/src/diff.cairo
alexandria/numeric/src/interpolate.cairo
alexandria/numeric/src/tests/cumsum_test.cairo
alexandria/numeric/src/tests/diff_test.cairo
alexandria/numeric/src/tests/interpolate_test.cairo
alexandria/numeric/src/tests/trapezoidal_rule_test.cairo
alexandria/numeric/src/trapezoidal_rule.cairo

The numeric and linalg functions allow only u32 types
Issue Number: #133 
The functions now allow all types of uint implementing the expected traits
Workload: ~ 1h

🐛 Make numeric and linalg features generic

---

Makefile

Follow up on #127, adds testing of `storage` to the Makefile's `test` target.
When running `make test`, the `test-storage` was not run. It is the first target/module that requires a `--starknet` arg to `cairo-test`, so it couldn't have been done like the rest of the stuff.
Running `make test` runs the tests for `storage` as well.
There's also a 2 new targets: `test-cairo` and `test-starknet`.
They group other targets as dependencies, former one is intended for non-starknet modules while the latter one for those that are starknet specific.
I'm no a Makefile expert by any stretch of the imagination so I'm open to any suggestions how this can be made better.

dev: test everything in Makefile

---

alexandria/storage/README.md

Follow up to #127, adding README documentation about `List`.
No docs. Code is docs.
Documentation in the README with a clear example how to use it, what does the interface look like (IMO it's pretty self-explanatory, so I didn't add any more description), guidance on how to implement `StorageSize` for custom types and some caveats.
Should be merged after #139 as the interface section already mentions the newly added `array` fn.

doc(storage): list

---

alexandria/storage/src/list.cairo
alexandria/storage/src/tests/list_test.cairo

List trait is not operable with function that accept Array trait.
To work around this, each user needs to implement his own conversion function
Issue Number: #138
`List.array()` offers a way for users to operate this conversion.
Workload ~ 1h

✨ Add List.array() feature

---

src/data_structures/array_ext.cairo
src/data_structures/merkle_tree.cairo
src/data_structures/stack.cairo
src/data_structures/tests/queue_test.cairo
src/data_structures/tests/stack_test.cairo
src/data_structures/vec.cairo
src/linalg/dot.cairo
src/math/collatz_sequence.cairo
src/math/ed25519.cairo
src/math/gcd_of_n_numbers.cairo
src/math/perfect_number.cairo
src/math/sha512.cairo
src/math/zellers_congruence.cairo
src/numeric/cumsum.cairo
src/numeric/diff.cairo
src/numeric/trapezoidal_rule.cairo
src/searching/binary_search.cairo
src/sorting/bubble_sort.cairo
src/sorting/sorting.cairo
src/storage/list.cairo

Updated:
- break (); => break;
- Option::None(()) => Option::None
- Option::None(_) => Option::None

Update all Option::None(()) to remove (())

---

src/storage/README.md
src/storage/Scarb.toml
src/storage/src/list.cairo
src/storage/src/tests/list_test.cairo

Additional improvements to `List` implementation.
* Removing the custom `StorageSize` trait. It's replaced by `Store::size` since in v2.1.0 it doesn't require an arg anymore.
* Using Poseidon hash instead of Pedersen (LegacyHash) since it's 10x cheaper.
No easy migration path but I'm guessing no one's using it in prod yet. Since it's a breaking change, I did bump the package version to `0.2.0`.
Also shortening the `test_append_get_many` test to go over less elements, should be about half as long while still testing the right behavior.

feat(storage): v2.1.0 improvements

---

src/math/src/lib.cairo

**Problem Description**
In the implementation of bitshifts in [lib.cairo](https://github.com/keep-starknet-strange/alexandria/blob/main/src/math/src/lib.cairo#L42-L50), the existing fpow function exhibits an overflow error when computing 2^n for n ≥ 64 using the generic function for u128.
**Details**
When we want to compute 2^n for n ≥ 64 using the generic function for u128, we encounter an overflow error. The error occurs in the last steps where we need to compute x * x, and x is greater than or equal to 2^64. Thus, x * x is greater than or equal to 2^128, leading to an overflow error.
**Proposed Solution**
The proposed solution is to modify the fpow function with a specific condition for n == 1. Below are the old and new code snippets:
**Old function code:**
```cairo
fn fpow(x: u128, n: …
```

fix fpow overflow

---

src/data_structures/README.md
src/data_structures/src/merkle_tree.cairo
src/data_structures/src/tests/merkle_tree_test.cairo

Issue Number: #169  
Issue Number: #170 
- A new implementation of the MerkleTree using poseidon hash method
- Add a `compute_proof` method to the MerkleTreeTrait to generate a proof based on leaves and an index
- Rename the previous merkle tree type from MerkleTree to MerkleTreeLegacy
- Merkle tree tests refactoring to clarify tests and add tests according to the new feature
Before the change you could just have:
```cairo
use alexandria_data_structures::merkle_tree::MerkleTreeTrait;
let mut merkle_tree = MerkleTreeTrait::new();
```
Now you must specify which kind of merkle tree you want (the legacy version or the new one):
```cairo
// The new version, using the poseidon hash method
use …
```

✨ Merkle tree generation

---

src/data_structures/src/array_ext.cairo
src/data_structures/src/tests/array_ext_test.cairo

Issue number [#172 ](https://github.com/keep-starknet-strange/alexandria/issues/172)
- Added the `unique` methods for `SpanTraitExt` & `ArrayTraitExt`,
- Added the corresponding unit tests.
For this little snippet:
```rust
let shortest: Span<T> = if (self.len() <= 1) || (ret.len() <= self.len()) {
ret.span()
} else {
self
};
```
Without the `self.len() <= 1` member some of my tests were failing.
Tried multiple things but couldn't find any better even though I feel like there's a more optimized solution... Curious to have your inputs! 🙏

feat: unique for arrays

---

src/math/src/lib.cairo
src/math/src/tests/math_test.cairo

Current implementation will return in premature overflows, for example: `BitShift::shl(255_u8, 1)` results in `u8_mul Overflow` while it should just return `254`.
`BitShift::shl(255_u8, 1) == 254` etc
-
-
-

fix BitShift::shl overflows

---

src/data_structures/src/bit_array.cairo
src/data_structures/src/lib.cairo
src/data_structures/src/tests.cairo
src/data_structures/src/tests/bit_array_test.cairo

- Adds a BitArray that can read/write unary bits as well as words of all sizes
- Supports encoding/decoding words in both big and little endian
- Packs bits within a bytes31 array
- Serialization and deserialization through Serde

Feat BitArray adds data structure for read/writing unary bits and encoding words in big/little endian notation

---

src/ascii/src/interger.cairo

Currently, when I use `ToAsciiArrayTrait::to_ascii_array()`, it behaves the same as `ToAsciiArrayTrait::to_inverse_ascii_array()` and returns reversed array (123.to_ascii_array() == array!['3', '2', '1']).
The reason behind it is that `to_ascii_array()` reverses the array but returns the unmodified array (because `ArrayTraitExt::reverse()` does not mutate)
- to_ascii_array() now returns ascii array with a correct order (123.to_ascii_array() == array!['1', '2', '3'])

Fix ToAsciiArrayTrait::to_ascii_array return reversed array

---

src/data_structures/Scarb.toml
src/data_structures/src/byte_array_ext.cairo
src/data_structures/src/tests/byte_array_ext_test.cairo

- Currently supports encoding and decoding from big endian ByteArray, which remains the default behaviour.
- Adds support for little endian encoding when storing or reading a ByteArray

feat: Little endian support for ByteArray extensions

---

src/data_structures/Scarb.toml
src/data_structures/src/byte_array_ext.cairo
src/data_structures/src/byte_array_reader.cairo
src/data_structures/src/tests/byte_array_ext_test.cairo
src/data_structures/src/tests/byte_array_reader_test.cairo

- Adds little endian byte order support for reading bytes from a ByteArray
Depends on changes made to `byte_array_ext.cairo` submitted in a previous PR

Feat: Little endian byte order support for ByteArrayReader

---

src/ascii/src/integer.cairo
src/bytes/src/utils.cairo
src/data_structures/src/array_ext.cairo
src/data_structures/src/stack.cairo
src/data_structures/src/tests/stack_test.cairo
src/data_structures/src/tests/vec_test.cairo
src/data_structures/src/vec.cairo
src/encoding/src/reversible.cairo
src/linalg/src/dot.cairo
src/merkle_tree/src/merkle_tree.cairo
src/numeric/src/cumsum.cairo
src/numeric/src/diff.cairo
src/numeric/src/interpolate.cairo
src/numeric/src/trapezoidal_rule.cairo
src/searching/src/binary_search.cairo
src/searching/src/dijkstra.cairo
src/sorting/src/bubble_sort.cairo
src/sorting/src/merge_sort.cairo
src/storage/src/list.cairo

Use anonymous generic impl parameters

---

src/math/src/lib.cairo
src/math/src/tests.cairo
src/math/src/tests/wad_ray_math_test.cairo
src/math/src/wad_ray_math.cairo

Handle Wad & Ray mul/div 
Issue Number: #211 
Add new functions to handle 18 & 27 decimals base maths

feat: add wad_ray_math with tests

---

Scarb.lock
Scarb.toml
src/storage/Scarb.toml

Bumped the version of the package following breaking changes in the API brought by #209

chore: bump version

---

src/sorting/src/bubble_sort.cairo
src/sorting/src/tests/bubble_sort_test.cairo

Issue Number: #217 
- Bubble sort don't infinite loop anymore when there is equal values
Also added a test to ensure the problem doesn't happen again

bugfix: fixed infinite loop bug on bubble sort

---

src/math/src/tests/mod_arithmetics_test.cairo

Adds basic tests for div_mod
No div_mod test.
Basic div_mod test added.
For 30 / 10 test,

div mod tests

---

src/math/src/mod_arithmetics.cairo

Optimisations for mod arithmetics.
Mod operations not as fast as they can be.
> ⚠️ `div_mod` test included here is added in PR #238
```
DIVISION OPTIMISATION (from core::math functions)
// div_mod_test     BEFORE gas usage est.: 97351914
// div_mod_test     BEFORE gas usage est.: 277900
MINOR optimisations (from inline)
// add_mod_1_test   BEFORE gas usage est.: 163180
// add_mod_1_test   AFTER gas usage est.:  159880
// add_mod_2_test   BEFORE gas usage est.: 109020
// add_mod_2_test   AFTER gas usage est.:  106820
// add_mod_p_test   BEFORE gas usage est.: 433980
// add_mod_p_test   AFTER gas usage est.:  425180
// mult_mod_1_test  BEFORE gas usage est.: 455340
// mult_mod_1_test  AFTER gas usage est.:  444940
// …
```

mod optimisations

---

src/bytes/src/bytes.cairo
src/data_structures/src/array_ext.cairo
src/data_structures/src/byte_appender.cairo
src/linalg/src/dot.cairo
src/math/src/ed25519.cairo
src/math/src/keccak256.cairo
src/math/src/sha512.cairo
src/merkle_tree/src/storage_proof.cairo
src/storage/src/list.cairo

This PR handles compiler warnings which are a new feature of the upcoming Cairo version. Today, it's visible only when compiling with the nightly version, i.e. building Alexandria after running the following (and removing the hardcoded Scarb version from .tools_versions):
```
asdf install scarb nightly-2024-01-13
asdb global scarb nightly-2024-01-13
```
ATM after running `Scarb build` with the nightly version, we get ~20 warnings. Most are due to unused variables, some due to unconsumed `Result`.
No warnings after compilation with nightly.

Fix: handel warnings

---

src/math/src/lib.cairo
src/math/src/tests/math_test.cairo

Individual functions for wrapping ops in uints.
Issue Number: #214
Adds a `WrappingMath` trait on math and implements it for uints. It provides `wrapping_add`, `wrapping_sub` and `wrapping_mul`, removing the need to use type-specific wrapping operations like `u64_wrapping_add`.
I added it directly to `math`, since I wasn't totally sure where would be the best module to keep this. Feel free to move / ask me to move it somewhere else.
(edit: Also adds individual traits for each operation: `WrappingAdd`, `WrappingSub` and `WrappingMul`)

feat: Add WrappingMath trait

---

src/math/src/signed_u256.cairo
src/math/src/tests/signed_u256_test.cairo

While code like the following is eventually understandable, it isn't as clearly obvious as the proposed one:
Before:
```rust
fn foo(value: i257) {
let mut x: u256 = 42;
if value.sign == true {
x += value.inner;
}
}
```
After: 
```rust
fn foo(value: i257) {
let mut x: u256 = 42;
if value.is_negative {
x += value.abs;
}
}
```

Simplify naming in `i257`

---

src/math/README.md
src/math/src/lib.cairo
src/math/src/tests.cairo
src/math/src/tests/trigonometry_test.cairo
src/math/src/trigonometry.cairo

This PR adds fast trigonometric functions (sin, cos, tan) to the library. Compared to standard trigonometric functions, fast trigonometric functions are computational and spacial efficient, with minor (acceptable errors).
- Add fast trigonometric functions (sin, cos, tan) to the library
- All tests are passed

feat: add fast trigonometric functions

---

Scarb.lock
src/sorting/README.md
src/sorting/Scarb.toml
src/sorting/src/lib.cairo
src/sorting/src/quick_sort.cairo
src/sorting/src/tests.cairo
src/sorting/src/tests/quick_sort_test.cairo

Add quick sort as a new sorting algorithm.
- Add quick sort as a new sorting algorithm
- All tests are passed

feat: add quick sort

---

src/numeric/README.md
src/numeric/src/cumprod.cairo
src/numeric/src/lib.cairo
src/numeric/src/tests.cairo
src/numeric/src/tests/cumprod_test.cairo

This PR adds a Cairo implementations of `cumprod()`.
- Calculating cumulative production (`cumprod()`) of a list.
- All tests are passed.

feat: add a Cairo implementations of `cumprod()`

---

src/searching/README.md
src/searching/src/bm_search.cairo
src/searching/src/lib.cairo
src/searching/src/tests.cairo
src/searching/src/tests/bm_search_test.cairo

This PR adds Boyer-Moore algorithm.
- searching pattern ByteArray in a text ByteArray using Boyer-Moore algorithm.

feat: add Boyer-Moore algorithm

---

src/searching/README.md
src/searching/src/levenshtein_distance.cairo
src/searching/src/lib.cairo
src/searching/src/tests.cairo
src/searching/src/tests/levenshtein_distance_test.cairo

This PR adds calculation of the Levenshtein distance of two ByteArray.
- calculating the Levenshtein distance of two ByteArray.

feat: add levenshtein distance calculator

---

src/math/README.md
src/math/src/lcm_of_n_numbers.cairo
src/math/src/lib.cairo
src/math/src/tests.cairo
src/math/src/tests/lcm_of_n_numbers_test.cairo

This PR adds LCM of N numbers.
- solving LCM of N numbers.

feat: add lcm of n numbers

---

Scarb.lock
src/linalg/README.md
src/linalg/Scarb.toml
src/linalg/src/lib.cairo
src/linalg/src/norm.cairo
src/linalg/src/tests.cairo
src/linalg/src/tests/norm_test.cairo

This PR adds `norm` operator.
- calculating Norm of a given list.

feat: add norm

---

src/linalg/src/tests/norm_test.cairo

This PR removes unnecessary `mut` in norm tests.
- remove `mut` in norm tests.

fix: remove unnecessary `mut` in norm tests

---

src/bytes/src/utils.cairo

The current implementation of array slices had a variable naming issue, where `len` and `end` seems to represent `end` and `len` respectively. Confusion leaked into the function description as well.
I also created a generic `array_slice`.

bug: array slice naming error and generic option

---

src/numeric/README.md

Current links lead to File not Found

chore: fixing path

---

src/merkle_tree/src/merkle_tree.cairo
src/merkle_tree/src/tests/merkle_tree_test.cairo

The current Poseidon hashing implementation for the merkle tree is incorrect. It uses 
```
let mut state = PoseidonTrait::new();
state = state.update(data1);
state = state.update(data2);
state.finalize()
```
Under the hood this actually hashes the elements twice  (once from the state update and once from finalization, see [corelib](https://github.com/starkware-libs/cairo/blob/main/corelib/src/poseidon.cairo)), the intended behaviours is that only one round of hashing is done (when hashing two elements). This is noted in https://docs.starknet.io/documentation/architecture_and_concepts/Cryptography/hash-functions/#poseidon_hash where by the hash of two elements is simply 
Also please see POC …

Fix merkle tree hashing for poseidon

---

src/math/src/i257.cairo
src/math/src/tests/i257_test.cairo

Fixing is_zero behaviour that was causing is_zero to sometimes return false when it was indeed zero

Fixing i257 is_zero()

---

Scarb.lock
src/bytes/src/bytes.cairo
src/bytes/src/tests/test_bytes.cairo
src/bytes/src/utils.cairo
src/encoding/README.md
src/encoding/Scarb.toml
src/encoding/src/lib.cairo
src/encoding/src/sol_abi.cairo
src/encoding/src/sol_abi/decode.cairo
src/encoding/src/sol_abi/encode.cairo
src/encoding/src/sol_abi/encode_as.cairo
src/encoding/src/sol_abi/sol_bytes.cairo
src/encoding/src/tests.cairo
src/encoding/src/tests/sol_abi.cairo

Added various traits/utils for supporting Solidity-like ABI encode functions. This includes the traits :
- `SolAbiEncodeTrait` : providing equivalents for Solidity `abi.encode` and `abi.encodePacked`
- `SolAbiEncodeSelectorTrait` : for Solidity `abi.encodeWithSelector`
- `SolAbiDecodeTrait` : for Solidity `abi.decode`
- `SolBytesTrait` : Providing utilities for easy conversion of types into Solidity-like `bytes1`, `bytes2`, ..., `bytes32` types
Also added some helpers for `alexandria_bytes::Bytes`, such as : 
- `Bytes` <-> Cairo's `ByteArray` & `bytes31` function options
- Debug & Display traits for `Bytes`, to allow printing `Bytes` as a hex string
Issue Number: #274

feat: Solidity ABI encode functions and utils

---

Scarb.lock
src/numeric/Scarb.toml
src/numeric/src/interpolate.cairo
src/numeric/src/tests.cairo
src/numeric/src/tests/interpolate_fast_test.cairo
src/numeric/src/tests/interpolate_test.cairo
src/searching/src/binary_search.cairo
src/searching/src/tests.cairo
src/searching/src/tests/binary_search_closest_test.cairo
src/searching/src/tests/binary_search_test.cairo

- implement a gas efficient implementation of interpolation
- implement binary search for closest element in sorted array
- fix interpolation error in the case of `Interpolation::ConstantLeft`
- additional tests are provided
Interpolation is gas inefficient with large arrays
closes #285
Fast interpolation complexity is now logarithmic (vs linear) in the number of array elements.
Bug fix in the original interpolation is corrected and more tests cases are provided.

Feat: fast interpolation bin search closest+bug fix

---

src/math/src/ed25519.cairo
src/math/src/mod_arithmetics.cairo
src/math/src/tests/ed25519_test.cairo

Adapted the format of the signature to something more representative and fixed an issue with signatures not being verified correctly. Added some test cases that were generated by the javascript lib Noble

fix: fix invalid signature verification

---

src/merkle_tree/src/storage_proof.cairo

In order to use those structs as calldata in contracts, Serde trait must be implemented

derive Serde trait to storage proof structs

---

src/bytes/Scarb.toml
src/bytes/src/bytes.cairo
src/bytes/src/lib.cairo
src/bytes/src/storage.cairo
src/bytes/src/tests.cairo
src/bytes/src/tests/test_bytes_store.cairo

Add `Store` implementation for the `Bytes` type to allow using `Bytes` in contract storage. Also added test cases.
Currently, when trying to use `Bytes` in contract storage you get errors like this :
```
starknet::Store::<Bytes>::write(
^***^
Error: Failed to compile test artifact, for detailed information go through the logs above
```
- Add storage functions to allow using `Bytes` in storage
- `Bytes` stored in the following format :
- Only the size in bytes is stored in the original address where the `Bytes` object is stored.
- The actual data is stored in chunks of 256 `u128` values in another location in storage determined by the hash of:
- The address storing the size of the bytes object.
- The chunk index.
- The …

feat: Bytes Store

---

src/math/README.md
src/math/src/bitmap.cairo
src/math/src/fast_power.cairo
src/math/src/lib.cairo
src/math/src/tests.cairo
src/math/src/tests/bitmap_test.cairo
src/math/src/tests/fast_power_test.cairo

No bitmap management
Issue Number: #295
- `bitmap::get_bit_at`
- `bitmap::set_bit_at`
- `bitmap::most_significant_bit`
- `bitmap::least_significant_bit`
- `bitmap::nearest_left_significant_bit`
- `bitmap::nearest_right_significant_bit`
- `bitmap::nearest_significant_bit`
`fast_power` has been renamed to `fast_power_mod` and a new `fast_power` derived from the previous one (without the mod operation) has been introduced.
`fast_power` has been made generic, revert from `while` to `loop` pattern to save gas (~10% for large power) and also to prevent overflow (an extra mul operation was done even if the remaining power was 0 due to while pattern).

feat(bitmap): add bitmap features

---

src/math/src/lib.cairo
src/math/src/tests.cairo
src/math/src/tests/u512_arithmetics_test.cairo
src/math/src/u512_arithmetics.cairo

Every operation requires immediate reduction.
Many mul/sqr operations on u256 are followed by add/sub which can be easily aggregated before doing a single mod operation. This requires u512 arithmetic. This PR adds addition and subtraction for u512.
Following functions are added
```rust
pub fn u512_add(lhs: u512, rhs: u512) -> u512;
pub fn u512_sub(lhs: u512, rhs: u512) -> u512;
```

u512 arithmetics

---

src/math/src/mod_arithmetics.cairo
src/math/src/tests/mod_arithmetics_test.cairo

> No dedicated u256 sqr, which can be done with one less u128 mul.
`pow_mod` uses `mult_mod`
> Instead of `mult_mod(x, x)`, call the more efficient `sqr_mod(x)`
>
> A new `u256_wide_sqr` which is largely identical to `u256_wide_mul` is added,
> <img width="1582" alt="image" src="https://github.com/keep-starknet-strange/alexandria/assets/11048263/3bf4223b-a751-4932-a9d4-77c6ba67abc1">
`pow_mod` uses `sqr_mod`
```diff
- test alexandria_math::tests::mod_arithmetics_test::pow_mod_test ... ok (gas usage est.: 27066340)
+ test alexandria_math::tests::mod_arithmetics_test::pow_mod_test ... ok (gas usage est.: 26160370)
- test alexandria_math::tests::mod_arithmetics_test::pow_mod_1_test ... ok (gas usage est.: 27015940)
+ test …
```

Mod pow and sqr

---

src/math/src/sha512.cairo

```diff
Collected 3 test(s) from alexandria_math package
Running 3 test(s) from src/
[PASS] alexandria_math::tests::sha512_test::test_size_zero (gas: ~20074)
-        steps: 2165513
+        steps: 735949
memory holes: 353718
builtins: ("range_check_builtin": 501826, "bitwise_builtin": 2025)
syscalls: ()
[PASS] alexandria_math::tests::sha512_test::test_sha512_size_one (gas: ~20073)
-        steps: 2165490
+        steps: 735926
memory holes: 353718
builtins: ("range_check_builtin": 501823, "bitwise_builtin": 2025)
syscalls: ()
[PASS] alexandria_math::tests::sha512_test::test_sha512_lorem_ipsum (gas: ~59599)
-        steps: 6427014
+        steps: 2149930
memory holes: 1055226
builtins: ("range_check_builtin": 1489975, "bitwise_builtin": …
```

sha512 optimisation

---

src/merkle_tree/src/merkle_tree.cairo

Gas of `scarb test -p alexandria_merkle_tree`
```
testing alexandria_merkle_tree ...
running 7 tests
test alexandria_merkle_tree::tests::merkle_tree_test::merkle_tree_poseidon_test ... ok (gas usage est.: 427910)
test alexandria_merkle_tree::tests::merkle_tree_test::merkle_tree_pedersen_test ... ok (gas usage est.: 484520)
test alexandria_merkle_tree::tests::storage_proof_test::balance_msb_proof_test ... ok (gas usage est.: 665518)
test alexandria_merkle_tree::tests::merkle_tree_test::regular_call_merkle_tree_pedersen::regular_call_merkle_tree_pedersen_test ... ok (gas usage est.: 484520)
test alexandria_merkle_tree::tests::storage_proof_test::balance_lsb_proof_test ... ok (gas usage est.: 1068614)
test …
```

Optimize merkle_tree

---

src/math/src/sha512.cairo

```diff
< [PASS] alexandria_math::tests::sha512_test::test_size_zero (gas: ~5698)
> [PASS] alexandria_math::tests::sha512_test::test_size_zero (gas: ~632)
<         steps: 735949
>         steps: 85153
<         memory holes: 73172
>         memory holes: 4849
<         builtins: ("range_check_builtin": 142428, "bitwise_builtin": 2025)
>         builtins: ("range_check_builtin": 15797, "bitwise_builtin": 2702)
< [PASS] alexandria_math::tests::sha512_test::test_sha512_size_one (gas: ~5697)
> [PASS] alexandria_math::tests::sha512_test::test_sha512_size_one (gas: ~633)
<         steps: 735926
>         steps: 85256
<         memory holes: 73172
>         memory holes: 4759
<         builtins: ("range_check_builtin": 142425, …
```

optim sha512 :rocket: :rocket: :rocket:

---

Scarb.lock
packages/math/Scarb.toml
packages/math/src/ed25519.cairo

The `math` package has a dependency on `data_structures` package only because the `ed25519.cairo` module uses 3 trivial functions from the `SpanTraitExt` trait. However, `data_structures` has a rather wild dependency tree by itself, so it pulls in `encoding`, `numeric`, `bytes` and `searching` 💀 
This PR removes the dependency of the `math` package on `data_structures` (and hence all its downstream deps) by adding (or rather, copy-pasting) two private functions (`dedup` and `reverse`) to the `ed25519.cairo` and replacing the third one (`concat`) by the use of `append_span` from Cairo core.
There's no regression in performance of the ed25519.
Before this change:
```shell
$ scarb test -f ed255
running 7 tests
test …
```

refactor: rm math package dependencies

---

packages/sorting/src/lib.cairo

The `pub` keyword is added to the merge_sort module because without this it cannot be used as a dependency due to the following error

bugfix: add `pub` to merge_sort module

---

packages/math/src/fast_root.cairo

Tiny minor fast_root.cairo doc update.
Equation seems off for a root function. Matches a power function.

chore: fast root docs equation

---

packages/bytes/src/bytes.cairo
packages/bytes/src/tests/test_bytes.cairo

read_bytes31 does not begin at the offset. This is incorrect standalone behavior and creates an infinite loop in the .into() function (from ByteTrait to ByteArray) if there is more than 61 bytes in the bytes struct
Starts at the right offset

Fix read_bytes31

---

packages/encoding/src/sol_abi/encode.cairo
packages/encoding/src/tests/sol_abi.cairo

When (ABI) encoding a ByteArray or Bytes with size multiple of 32, we try to add an unnecessary 32 byte padding and end up with the following panic:
> Panicked with 0x496e646578206f7574206f6620626f756e6473 ('Index out of bounds').
If the size is multiple of 32, skip padding. This avoids the panic.
N/A

fix: byte array ABI encoding
